# Generated by Django 3.1.5 on 2021-02-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_auto_20210131_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('False', 'False'), ('True', 'True')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('False', 'False'), ('True', 'True')], max_length=20),
        ),
    ]
